export const products = [
  // Поломоичные Машины
  {
    id: 1,
    title: "Машина для уборки A",
    categoryId: 1,
    price: 120000000,
    image: "/home/product-1.png",
    discount: 10,
    description: "Эффективная машина для уборки больших площадей.",
    brandName: "CleanMaster",
  },
  {
    id: 2,
    title: "Машина для уборки B",
    categoryId: 1,
    price: 150000000,
    image: "/home/product-2.png",
    status: "Tavsiya qilamiz",
    description: "Мощная уборочная машина с низким уровнем шума.",
    brandName: "EcoClean",
  },
  {
    id: 3,
    title: "Машина для уборки C",
    categoryId: 1,
    price: 140000000,
    image: "/home/product-3.png",
    discount: 15,
    description: "Высокопроизводительная модель для профессионалов.",
    brandName: "ProClean",
  },
  {
    id: 4,
    title: "Машина для уборки D",
    categoryId: 1,
    price: 135000000,
    image: "/home/product-4.png",
    discount: 5,
    description: "Компактная и удобная в использовании.",
    brandName: "SpeedClean",
  },
  {
    id: 5,
    title: "Машина для уборки E",
    categoryId: 1,
    price: 155000000,
    image: "/home/product-1.png",
    status: "Tavsiya qilamiz",
    description: "Инновационная уборочная техника с большим ресурсом.",
    brandName: "PowerClean",
  },
  {
    id: 6,
    title: "Машина для уборки F",
    categoryId: 1,
    price: 145000000,
    image: "/home/product-2.png",
    discount: 10,
    description: "Надежная модель для ежедневного использования.",
    brandName: "DailyClean",
  },
  {
    id: 7,
    title: "Машина для уборки G",
    categoryId: 1,
    price: 125000000,
    image: "/home/product-3.png",
    discount: 20,
    description: "Универсальная уборочная техника для всех типов покрытий.",
    brandName: "FlexiClean",
  },
  {
    id: 8,
    title: "Машина для уборки H",
    categoryId: 1,
    price: 160000000,
    image: "/home/product-4.png",
    status: "Maxsus taklif",
    description: "Экономичная модель с высокой мощностью.",
    brandName: "EcoPro",
  },
  {
    id: 9,
    title: "Машина для уборки I",
    categoryId: 1,
    price: 170000000,
    image: "/home/product-1.png",
    status: "Tavsiya qilamiz",
    description: "Профессиональная уборочная машина премиум-класса.",
    brandName: "TopClean",
  },

  // Уборный инвентар
  {
    id: 10,
    title: "Инвентарь для уборки A",
    categoryId: 2,
    price: 30000000,
    image: "/home/product-2.png",
    status: "Maxsus taklif",
    description: "Прочный инвентарь для всех типов уборки.",
    brandName: "ToolPro",
  },
  {
    id: 11,
    title: "Инвентарь для уборки B",
    categoryId: 2,
    price: 35000000,
    image: "/home/product-3.png",
    discount: 10,
    description: "Эргономичный дизайн для удобной работы.",
    brandName: "HandyClean",
  },
  {
    id: 12,
    title: "Инвентарь для уборки C",
    categoryId: 2,
    price: 40000000,
    image: "/home/product-4.png",
    discount: 5,
    description: "Универсальный инвентарь для влажной и сухой уборки.",
    brandName: "MultiTool",
  },
  {
    id: 13,
    title: "Инвентарь для уборки D",
    categoryId: 2,
    price: 45000000,
    image: "/home/product-1.png",
    status: "Maxsus taklif",
    description: "Идеальное решение для профессиональных уборок.",
    brandName: "ProTool",
  },
  {
    id: 14,
    title: "Инвентарь для уборки E",
    categoryId: 2,
    price: 50000000,
    image: "/home/product-2.png",
    status: "Maxsus taklif",
    description: "Легкий и прочный инвентарь.",
    brandName: "LiteClean",
  },

  // Профессионалные пылесосы
  {
    id: 15,
    title: "Пылесос профессиональный A",
    categoryId: 3,
    price: 80000000,
    image: "/home/product-3.png",
    discount: 5,
    description: "Эффективная уборка с минимальными усилиями.",
    brandName: "VacuumPro",
  },
  {
    id: 16,
    title: "Пылесос профессиональный B",
    categoryId: 3,
    price: 95000000,
    image: "/home/product-4.png",
    status: "Tavsiya qilamiz",
    description: "Эффективная уборка с минимальными усилиями.",
    brandName: "SilentVac",
  },
  {
    id: 17,
    title: "Пылесос профессиональный C",
    categoryId: 3,
    price: 100000000,
    image: "/home/product-1.png",
    discount: 15,
    description: "Максимальная производительность для больших площадей.",
    brandName: "MegaVac",
  },
  {
    id: 18,
    title: "Пылесос профессиональный D",
    categoryId: 3,
    price: 110000000,
    image: "/home/product-2.png",
    status: "Maxsus taklif",
    description: "Компактная модель с высокой мощностью.",
    brandName: "CompactVac",
  },
  {
    id: 19,
    title: "Пылесос профессиональный E",
    categoryId: 3,
    price: 115000000,
    image: "/home/product-3.png",
    discount: 10,
    description: "Идеально подходит для офисных помещений.",
    brandName: "OfficeVac",
  },
  {
    id: 20,
    title: "Пылесос профессиональный F",
    categoryId: 3,
    price: 120000000,
    image: "/home/product-4.png",
    status: "Maxsus taklif",
    description: "Прочная конструкция для долгого срока службы.",
    brandName: "DurableVac",
  },
  {
    id: 21,
    title: "Пылесос профессиональный G",
    categoryId: 3,
    price: 125000000,
    image: "/home/product-1.png",
    discount: 20,
    description: "Высокая мощность для любых задач.",
    brandName: "HighPowerVac",
  },
  {
    id: 22,
    title: "Пылесос профессиональный H",
    categoryId: 3,
    price: 130000000,
    image: "/home/product-2.png",
    status: "Maxsus taklif",
    description: "Мобильная модель для удобного использования.",
    brandName: "MobileVac",
  },
  {
    id: 23,
    title: "Пылесос профессиональный I",
    categoryId: 3,
    price: 135000000,
    image: "/home/product-3.png",
    status: "Maxsus taklif",
    description: "Компактный дизайн с мощным двигателем.",
    brandName: "CompactPowerVac",
  },
  {
    id: 24,
    title: "Пылесос профессиональный J",
    categoryId: 3,
    price: 140000000,
    image: "/home/product-4.png",
    discount: 20,
    description: "Инновационные технологии для профессиональной уборки.",
    brandName: "InnovVac",
  },
  {
    id: 25,
    title: "Пылесос профессиональный K",
    categoryId: 3,
    price: 145000000,
    image: "/home/product-1.png",
    status: "Maxsus taklif",
    description: "Современная модель с функцией самоочистки.",
    brandName: "SmartVac",
  },
  {
    id: 26,
    title: "Пылесос профессиональный L",
    categoryId: 3,
    price: 150000000,
    image: "/home/product-2.png",
    status: "Maxsus taklif",
    description: "Надежность и мощность в каждой детали.",
    brandName: "ReliableVac",
  },

  // Моющые средства
  {
    id: 27,
    title: "Моющее средство A",
    categoryId: 4,
    price: 2000000,
    image: "/home/product-3.png",
    status: "Maxsus taklif",
    description: "Эффективное средство для всех типов поверхностей.",
    brandName: "CleanSolution",
  },
  {
    id: 28,
    title: "Моющее средство B",
    categoryId: 4,
    price: 2500000,
    image: "/home/product-4.png",
    discount: 5,
    description: "Быстрое удаление загрязнений.sdfghuhkhghgyhgh",
    brandName: "FastClean",
  },
  {
    id: 29,
    title: "Моющее средство C",
    categoryId: 4,
    price: 3000000,
    image: "/home/product-1.png",
    status: "Maxsus taklif",
    description: "Экономичный расход и высокая эффективность.",
    brandName: "EcoCleanser",
  },

  // Поломоичные Машины 2
  {
    id: 30,
    title: "Машина для уборки 2A",
    categoryId: 5,
    price: 130000000,
    image: "/home/product-2.png",
    status: "Maxsus taklif",
    description: "Усовершенствованная модель с дополнительными функциями.",
    brandName: "AdvanceClean",
  },
  {
    id: 31,
    title: "Машина для уборки 2B",
    categoryId: 5,
    price: 140000000,
    image: "/home/product-3.png",
    status: "Maxsus taklif",
    description: "Максимальная производительность с минимальными затратами.",
    brandName: "MaxiClean",
  },
];
